name: Android Demo Build

on:
  workflow_dispatch:
    inputs:
      build_profile:
        description: "EAS build profile"
        required: true
        default: "preview"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd frontend/mobile-app
          npm install

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      
      - name: 🚀 Build App
        run: eas build --platform ios --non-interactive
      - name: Print build link
        run: echo "Check Expo dashboard for APK download"
